content = open('templates/home.html', encoding='utf-8').read()
print("FIRST 300 chars:")
print(content[:300])
print("---")
print("LAST 300 chars:")
print(content[-300:])
print("---")
print("block content count:", content.count('block content'))
print("extends count:", content.count('extends'))