# Generated by Django 6.0.5 on 2026-06-01 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_score', models.IntegerField(default=0)),
                ('ats_score', models.IntegerField(default=0)),
                ('extracted_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('education_score', models.IntegerField(default=0)),
                ('experience_score', models.IntegerField(default=0)),
                ('skills_score', models.IntegerField(default=0)),
                ('formatting_score', models.IntegerField(default=0)),
                ('keyword_density', models.FloatField(default=0.0)),
                ('detected_role', models.CharField(blank=True, max_length=100)),
                ('experience_level', models.CharField(blank=True, max_length=50)),
                ('raw_text', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='analyzer.resume')),
            ],
        ),
    ]
